### ISSUE TITLE
Stripe Element Card not working on Vue 3

### ISSUE THREAD

**Issue by JJordan0C** [vue-stripe/vue-stripe#289]
**Describe the bug**
The bug appears from the moment I go to implement vue-stripe within my project, I don't know how many bugs I have found, but every time I tried to add the plugin an error would pop up and yet the documentation seems to be very clear, but when I do .use (Plugin, options), the first errors pop up (I also added the stripe.js link).
After that I tried to use the elements without adding the plugin to my app, but obviously another error appears, I've been trying for hours now and I can't find a solution, now I leave you the errors of all 2 cases.
I hope someone will be able to help me, thanks.
(Sorry for my bad english)

**To Reproduce First**
1. Follow this instruction: https://vuestripe.com/stripe-plugin/getting-started

**To Reproduce Second**
1. Follow this instruction: https://vuestripe.com/stripe-elements/card or this: https://vuestripe.com/stripe-elements/separate-card-fields (Step 3, because step 1 and 2 is equal to getting-started)

**Expected behavior**
II wish I could use this plugin

**Screenshots**
![vue-stripe-first-error](https://user-images.githubusercontent.com/69581081/178524191-39462264-cd09-4856-955e-895272f6a10c.PNG)

![vue-stripe-second-error](https://user-images.githubusercontent.com/69581081/178523479-75b7bcf3-4535-4724-a4c8-05029fdcd72b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Comment by AdamMoroff75** [comment]
Im getting the same error.  Vue 3 using Quasar framework. 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__ (index.js:7:9064)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5580:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:1)
    at instance.update (runtime-core.esm-bundler.js:5694:1)
    at setupRenderEffect (runtime-core.esm-bundler.js:5708:1)
    at mountComponent (runtime-core.esm-bundler.js:5490:1)
    at processComponent (runtime-core.esm-bundler.js:5448:1)
    at patch (runtime-core.esm-bundler.js:5038:1)
    at mountChildren (runtime-core.esm-bundler.js:5234:1)
```

**Comment by tad0xe** [comment]
i'm getting Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c') in vue 3

**Comment by adbci** [comment]
Same here

**Comment by LiuJQ** [comment]
Same exception

**Comment by 9mm** [comment]
I get this, and underneath that the `_c` errors above

runtime-core.esm-bundler.js?d2dd:38 [Vue warn]: Property "$createElement" was accessed during render but is not defined on instance. 
  at <Anonymous ref="cardInputStripe" pk="xxxxx" onToken=fn<bound onTokenCreate> > 
  at <WrapperCheckout step-options= (2) [{…}, {…}] step-selected="review" > 
  at <ViewCheckout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key="/checkout" > 
  at <AppContent> 
  at <LayoutApp onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterVie

**Comment by 9mm** [comment]
Also, if this is officially under Stripe's umbrella, how are they not concerned more that this issue was created 2+ months ago and still doesn't work under vue 3?

https://stripe.com/partners/directory/vue-stripe

**Comment by codegeek1001** [comment]
From the documentation, it doesn't seem like it is ready for Vue 3 yet.

**Comment by 9mm** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/1386207/189974273-6b9a7742-82b6-4147-b3e6-afba9a3350b2.png">

**Comment by 9mm** [comment]
I'm wrong then, I can't find it. My bad. Maybe it was a previous vue card plugin I tried that I am confusing with this one, but I no longer see vue 3 listed out wherever I saw it.

**Comment by hassamsaeed-qbatch** [comment]
i'm getting Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c') in vue 3

**Comment by walmartwarlord** [comment]
man just use the composable based package for this

https://github.com/frandiox/vue-use-stripe

ez af

**Comment by walmartwarlord** [comment]
Here are better alternatives that works with Vue 3:

- https://github.com/ectoflow/vue-stripe-js
- https://github.com/frandiox/vue-use-stripe

Deprecate this package already

**Comment by jofftiquez** [comment]
Hi there! 👋

Great news! **Vue Stripe v5 with full Vue 3 support is now available on npm!** 🎉

```bash
npm install @vue-stripe/vue-stripe
```

We sincerely apologize for the long wait. We know many of you have been patiently waiting for Vue 3 support, and we truly appreciate your patience and understanding throughout this process.

The new version includes:
- Full Vue 3 support
- Modern Stripe Elements (Payment Element, Express Checkout, Link Authentication, Address Element)
- TypeScript support
- Composables API (`useStripe`, `useStripeElements`, `usePaymentIntent`, etc.)
- And much more!

Check out the documentation and let us know if you have any questions about the new version.

Thank you for your patience and continued support! ❤️

---
*This issue is being closed as part of the v5 release. If you believe your issue is still relevant with the new version, please open a new issue with details.*
